---
  - name: Copy files
    become: true
    copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
  - name: Unarchive
    become: true
    shell : |        
        tar xvzf artifact.tar.gz -C .
  - name: "run server"
    become: true
    shell : |
        pm2 stop default
        pm2 start npm -- start
    

